package main

import (
	"bytes"
	"text/template"
)

type Template struct{}

func NewTemplate() *Template {
	return &Template{}
}

func (t *Template) Render(data any) (string, error) {
	tpl, err := template.New("template").Parse(input)
	if err != nil {
		return "", err
	}

	buf := bytes.NewBuffer(nil)
	err = tpl.Execute(buf, data)
	if err != nil {
		return "", err
	}

	return buf.String(), nil
}

var input = `// Code generated by go generate; DO NOT EDIT.
package config

const (
	ServerURL = "{{ .Server.URL }}"
	ServerUsername = "{{ .Server.Username }}"
	ServerPassword = "{{ .Server.Password }}"
)

const (
	ServiceName = "{{ .Service.Name }}"
	ServiceWorkerName = "{{ .Service.Name }}"
	ServiceVersion = "{{ .Service.Version }}"
)
`

type Data struct {
	Server struct {
		URL      string `yaml:"url"`
		Username string `yaml:"username"`
		Password string `yaml:"password"`
	} `yaml:"server"`
	Service struct {
		Name    string `yaml:"name"`
		Version string `yaml:"version"`
	} `yaml:"service"`
}
