package exec

/*
import (
	"bytes"
	"text/template"
)

type templateData struct{}

const templateString = `// Code generated by go generate; DO NOT EDIT.
package config
`

func RenderTemplate(tstr string, data any) ([]byte, error) {
	tpl, err := template.New("template").Parse(tstr)
	if err != nil {
		return nil, err
	}

	buf := bytes.NewBuffer(nil)
	err = tpl.Execute(buf, data)
	if err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}
*/
