// Code generated by capnpc-go. DO NOT EDIT.

package capnp

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	strconv "strconv"
)

// Constants defined in proto.capnp.
const (
	StartWorkerT        = "FJ.API.WORKER.START.%s.%s"
	StopWorkerT         = "FJ.API.WORKER.STOP.%s.%s"
	WriteWorkerStdinT   = "FJ.API.WORKER.WRITE.STDIN.%s.%s"
	WriteWorkerStdoutT  = "FJ.API.WORKER.WRITE.STDOUT.%s.%s"
	UpdateWorkerStatusT = "FJ.API.WORKER.UPDATE.STATUS.%s.%s"
	UpdateClientInfoT   = "FJ.API.CLIENT.UPDATE.INFO.%s"
	ReplyMessageT       = "FJ.API.MESSAGE.REPLY.%s.%s"
)

type StartWorkerRequest capnp.Struct

// StartWorkerRequest_TypeID is the unique identifier for the type StartWorkerRequest.
const StartWorkerRequest_TypeID = 0x9892032ea4e69c6b

func NewStartWorkerRequest(s *capnp.Segment) (StartWorkerRequest, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3})
	return StartWorkerRequest(st), err
}

func NewRootStartWorkerRequest(s *capnp.Segment) (StartWorkerRequest, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3})
	return StartWorkerRequest(st), err
}

func ReadRootStartWorkerRequest(msg *capnp.Message) (StartWorkerRequest, error) {
	root, err := msg.Root()
	return StartWorkerRequest(root.Struct()), err
}

func (s StartWorkerRequest) String() string {
	str, _ := text.Marshal(0x9892032ea4e69c6b, capnp.Struct(s))
	return str
}

func (s StartWorkerRequest) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (StartWorkerRequest) DecodeFromPtr(p capnp.Ptr) StartWorkerRequest {
	return StartWorkerRequest(capnp.Struct{}.DecodeFromPtr(p))
}

func (s StartWorkerRequest) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s StartWorkerRequest) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s StartWorkerRequest) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s StartWorkerRequest) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s StartWorkerRequest) Command() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s StartWorkerRequest) HasCommand() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s StartWorkerRequest) CommandBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s StartWorkerRequest) SetCommand(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s StartWorkerRequest) Args() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return capnp.TextList(p.List()), err
}

func (s StartWorkerRequest) HasArgs() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s StartWorkerRequest) SetArgs(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewArgs sets the args field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s StartWorkerRequest) NewArgs(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}
func (s StartWorkerRequest) Env() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return capnp.TextList(p.List()), err
}

func (s StartWorkerRequest) HasEnv() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s StartWorkerRequest) SetEnv(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(2, v.ToPtr())
}

// NewEnv sets the env field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s StartWorkerRequest) NewEnv(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(2, l.ToPtr())
	return l, err
}

// StartWorkerRequest_List is a list of StartWorkerRequest.
type StartWorkerRequest_List = capnp.StructList[StartWorkerRequest]

// NewStartWorkerRequest creates a new list of StartWorkerRequest.
func NewStartWorkerRequest_List(s *capnp.Segment, sz int32) (StartWorkerRequest_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3}, sz)
	return capnp.StructList[StartWorkerRequest](l), err
}

// StartWorkerRequest_Future is a wrapper for a StartWorkerRequest promised by a client call.
type StartWorkerRequest_Future struct{ *capnp.Future }

func (f StartWorkerRequest_Future) Struct() (StartWorkerRequest, error) {
	p, err := f.Future.Ptr()
	return StartWorkerRequest(p.Struct()), err
}

type StartWorkerResponse capnp.Struct

// StartWorkerResponse_TypeID is the unique identifier for the type StartWorkerResponse.
const StartWorkerResponse_TypeID = 0xc5f4047bf39fa88d

func NewStartWorkerResponse(s *capnp.Segment) (StartWorkerResponse, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return StartWorkerResponse(st), err
}

func NewRootStartWorkerResponse(s *capnp.Segment) (StartWorkerResponse, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return StartWorkerResponse(st), err
}

func ReadRootStartWorkerResponse(msg *capnp.Message) (StartWorkerResponse, error) {
	root, err := msg.Root()
	return StartWorkerResponse(root.Struct()), err
}

func (s StartWorkerResponse) String() string {
	str, _ := text.Marshal(0xc5f4047bf39fa88d, capnp.Struct(s))
	return str
}

func (s StartWorkerResponse) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (StartWorkerResponse) DecodeFromPtr(p capnp.Ptr) StartWorkerResponse {
	return StartWorkerResponse(capnp.Struct{}.DecodeFromPtr(p))
}

func (s StartWorkerResponse) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s StartWorkerResponse) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s StartWorkerResponse) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s StartWorkerResponse) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s StartWorkerResponse) Error() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s StartWorkerResponse) HasError() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s StartWorkerResponse) ErrorBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s StartWorkerResponse) SetError(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// StartWorkerResponse_List is a list of StartWorkerResponse.
type StartWorkerResponse_List = capnp.StructList[StartWorkerResponse]

// NewStartWorkerResponse creates a new list of StartWorkerResponse.
func NewStartWorkerResponse_List(s *capnp.Segment, sz int32) (StartWorkerResponse_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[StartWorkerResponse](l), err
}

// StartWorkerResponse_Future is a wrapper for a StartWorkerResponse promised by a client call.
type StartWorkerResponse_Future struct{ *capnp.Future }

func (f StartWorkerResponse_Future) Struct() (StartWorkerResponse, error) {
	p, err := f.Future.Ptr()
	return StartWorkerResponse(p.Struct()), err
}

type StopWorkerRequest capnp.Struct

// StopWorkerRequest_TypeID is the unique identifier for the type StopWorkerRequest.
const StopWorkerRequest_TypeID = 0xb15c44a86e45d3b0

func NewStopWorkerRequest(s *capnp.Segment) (StopWorkerRequest, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return StopWorkerRequest(st), err
}

func NewRootStopWorkerRequest(s *capnp.Segment) (StopWorkerRequest, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return StopWorkerRequest(st), err
}

func ReadRootStopWorkerRequest(msg *capnp.Message) (StopWorkerRequest, error) {
	root, err := msg.Root()
	return StopWorkerRequest(root.Struct()), err
}

func (s StopWorkerRequest) String() string {
	str, _ := text.Marshal(0xb15c44a86e45d3b0, capnp.Struct(s))
	return str
}

func (s StopWorkerRequest) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (StopWorkerRequest) DecodeFromPtr(p capnp.Ptr) StopWorkerRequest {
	return StopWorkerRequest(capnp.Struct{}.DecodeFromPtr(p))
}

func (s StopWorkerRequest) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s StopWorkerRequest) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s StopWorkerRequest) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s StopWorkerRequest) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// StopWorkerRequest_List is a list of StopWorkerRequest.
type StopWorkerRequest_List = capnp.StructList[StopWorkerRequest]

// NewStopWorkerRequest creates a new list of StopWorkerRequest.
func NewStopWorkerRequest_List(s *capnp.Segment, sz int32) (StopWorkerRequest_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[StopWorkerRequest](l), err
}

// StopWorkerRequest_Future is a wrapper for a StopWorkerRequest promised by a client call.
type StopWorkerRequest_Future struct{ *capnp.Future }

func (f StopWorkerRequest_Future) Struct() (StopWorkerRequest, error) {
	p, err := f.Future.Ptr()
	return StopWorkerRequest(p.Struct()), err
}

type StopWorkerResponse capnp.Struct

// StopWorkerResponse_TypeID is the unique identifier for the type StopWorkerResponse.
const StopWorkerResponse_TypeID = 0xdea9ade321ec73b3

func NewStopWorkerResponse(s *capnp.Segment) (StopWorkerResponse, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return StopWorkerResponse(st), err
}

func NewRootStopWorkerResponse(s *capnp.Segment) (StopWorkerResponse, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return StopWorkerResponse(st), err
}

func ReadRootStopWorkerResponse(msg *capnp.Message) (StopWorkerResponse, error) {
	root, err := msg.Root()
	return StopWorkerResponse(root.Struct()), err
}

func (s StopWorkerResponse) String() string {
	str, _ := text.Marshal(0xdea9ade321ec73b3, capnp.Struct(s))
	return str
}

func (s StopWorkerResponse) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (StopWorkerResponse) DecodeFromPtr(p capnp.Ptr) StopWorkerResponse {
	return StopWorkerResponse(capnp.Struct{}.DecodeFromPtr(p))
}

func (s StopWorkerResponse) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s StopWorkerResponse) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s StopWorkerResponse) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s StopWorkerResponse) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s StopWorkerResponse) Error() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s StopWorkerResponse) HasError() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s StopWorkerResponse) ErrorBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s StopWorkerResponse) SetError(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// StopWorkerResponse_List is a list of StopWorkerResponse.
type StopWorkerResponse_List = capnp.StructList[StopWorkerResponse]

// NewStopWorkerResponse creates a new list of StopWorkerResponse.
func NewStopWorkerResponse_List(s *capnp.Segment, sz int32) (StopWorkerResponse_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[StopWorkerResponse](l), err
}

// StopWorkerResponse_Future is a wrapper for a StopWorkerResponse promised by a client call.
type StopWorkerResponse_Future struct{ *capnp.Future }

func (f StopWorkerResponse_Future) Struct() (StopWorkerResponse, error) {
	p, err := f.Future.Ptr()
	return StopWorkerResponse(p.Struct()), err
}

type UpdateWorkerStatus capnp.Struct

// UpdateWorkerStatus_TypeID is the unique identifier for the type UpdateWorkerStatus.
const UpdateWorkerStatus_TypeID = 0xa62a70011c9fd5df

func NewUpdateWorkerStatus(s *capnp.Segment) (UpdateWorkerStatus, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return UpdateWorkerStatus(st), err
}

func NewRootUpdateWorkerStatus(s *capnp.Segment) (UpdateWorkerStatus, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return UpdateWorkerStatus(st), err
}

func ReadRootUpdateWorkerStatus(msg *capnp.Message) (UpdateWorkerStatus, error) {
	root, err := msg.Root()
	return UpdateWorkerStatus(root.Struct()), err
}

func (s UpdateWorkerStatus) String() string {
	str, _ := text.Marshal(0xa62a70011c9fd5df, capnp.Struct(s))
	return str
}

func (s UpdateWorkerStatus) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (UpdateWorkerStatus) DecodeFromPtr(p capnp.Ptr) UpdateWorkerStatus {
	return UpdateWorkerStatus(capnp.Struct{}.DecodeFromPtr(p))
}

func (s UpdateWorkerStatus) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s UpdateWorkerStatus) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s UpdateWorkerStatus) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s UpdateWorkerStatus) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s UpdateWorkerStatus) Status() int64 {
	return int64(capnp.Struct(s).Uint64(0))
}

func (s UpdateWorkerStatus) SetStatus(v int64) {
	capnp.Struct(s).SetUint64(0, uint64(v))
}

// UpdateWorkerStatus_List is a list of UpdateWorkerStatus.
type UpdateWorkerStatus_List = capnp.StructList[UpdateWorkerStatus]

// NewUpdateWorkerStatus creates a new list of UpdateWorkerStatus.
func NewUpdateWorkerStatus_List(s *capnp.Segment, sz int32) (UpdateWorkerStatus_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[UpdateWorkerStatus](l), err
}

// UpdateWorkerStatus_Future is a wrapper for a UpdateWorkerStatus promised by a client call.
type UpdateWorkerStatus_Future struct{ *capnp.Future }

func (f UpdateWorkerStatus_Future) Struct() (UpdateWorkerStatus, error) {
	p, err := f.Future.Ptr()
	return UpdateWorkerStatus(p.Struct()), err
}

type UpdateWorkerStdio capnp.Struct

// UpdateWorkerStdio_TypeID is the unique identifier for the type UpdateWorkerStdio.
const UpdateWorkerStdio_TypeID = 0xa76a3a9604a9e962

func NewUpdateWorkerStdio(s *capnp.Segment) (UpdateWorkerStdio, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return UpdateWorkerStdio(st), err
}

func NewRootUpdateWorkerStdio(s *capnp.Segment) (UpdateWorkerStdio, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return UpdateWorkerStdio(st), err
}

func ReadRootUpdateWorkerStdio(msg *capnp.Message) (UpdateWorkerStdio, error) {
	root, err := msg.Root()
	return UpdateWorkerStdio(root.Struct()), err
}

func (s UpdateWorkerStdio) String() string {
	str, _ := text.Marshal(0xa76a3a9604a9e962, capnp.Struct(s))
	return str
}

func (s UpdateWorkerStdio) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (UpdateWorkerStdio) DecodeFromPtr(p capnp.Ptr) UpdateWorkerStdio {
	return UpdateWorkerStdio(capnp.Struct{}.DecodeFromPtr(p))
}

func (s UpdateWorkerStdio) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s UpdateWorkerStdio) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s UpdateWorkerStdio) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s UpdateWorkerStdio) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s UpdateWorkerStdio) Data() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s UpdateWorkerStdio) HasData() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s UpdateWorkerStdio) SetData(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

// UpdateWorkerStdio_List is a list of UpdateWorkerStdio.
type UpdateWorkerStdio_List = capnp.StructList[UpdateWorkerStdio]

// NewUpdateWorkerStdio creates a new list of UpdateWorkerStdio.
func NewUpdateWorkerStdio_List(s *capnp.Segment, sz int32) (UpdateWorkerStdio_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[UpdateWorkerStdio](l), err
}

// UpdateWorkerStdio_Future is a wrapper for a UpdateWorkerStdio promised by a client call.
type UpdateWorkerStdio_Future struct{ *capnp.Future }

func (f UpdateWorkerStdio_Future) Struct() (UpdateWorkerStdio, error) {
	p, err := f.Future.Ptr()
	return UpdateWorkerStdio(p.Struct()), err
}

type UpdateClientInfo capnp.Struct

// UpdateClientInfo_TypeID is the unique identifier for the type UpdateClientInfo.
const UpdateClientInfo_TypeID = 0xa073b10fb899cbb0

func NewUpdateClientInfo(s *capnp.Segment) (UpdateClientInfo, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4})
	return UpdateClientInfo(st), err
}

func NewRootUpdateClientInfo(s *capnp.Segment) (UpdateClientInfo, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4})
	return UpdateClientInfo(st), err
}

func ReadRootUpdateClientInfo(msg *capnp.Message) (UpdateClientInfo, error) {
	root, err := msg.Root()
	return UpdateClientInfo(root.Struct()), err
}

func (s UpdateClientInfo) String() string {
	str, _ := text.Marshal(0xa073b10fb899cbb0, capnp.Struct(s))
	return str
}

func (s UpdateClientInfo) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (UpdateClientInfo) DecodeFromPtr(p capnp.Ptr) UpdateClientInfo {
	return UpdateClientInfo(capnp.Struct{}.DecodeFromPtr(p))
}

func (s UpdateClientInfo) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s UpdateClientInfo) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s UpdateClientInfo) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s UpdateClientInfo) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s UpdateClientInfo) Username() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s UpdateClientInfo) HasUsername() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s UpdateClientInfo) UsernameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s UpdateClientInfo) SetUsername(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s UpdateClientInfo) Hostname() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s UpdateClientInfo) HasHostname() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s UpdateClientInfo) HostnameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s UpdateClientInfo) SetHostname(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s UpdateClientInfo) System() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s UpdateClientInfo) HasSystem() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s UpdateClientInfo) SystemBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s UpdateClientInfo) SetSystem(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s UpdateClientInfo) Address() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s UpdateClientInfo) HasAddress() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s UpdateClientInfo) AddressBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s UpdateClientInfo) SetAddress(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

// UpdateClientInfo_List is a list of UpdateClientInfo.
type UpdateClientInfo_List = capnp.StructList[UpdateClientInfo]

// NewUpdateClientInfo creates a new list of UpdateClientInfo.
func NewUpdateClientInfo_List(s *capnp.Segment, sz int32) (UpdateClientInfo_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4}, sz)
	return capnp.StructList[UpdateClientInfo](l), err
}

// UpdateClientInfo_Future is a wrapper for a UpdateClientInfo promised by a client call.
type UpdateClientInfo_Future struct{ *capnp.Future }

func (f UpdateClientInfo_Future) Struct() (UpdateClientInfo, error) {
	p, err := f.Future.Ptr()
	return UpdateClientInfo(p.Struct()), err
}

type Message capnp.Struct
type Message_content Message
type Message_content_Which uint16

const (
	Message_content_Which_startWorkerRequest  Message_content_Which = 0
	Message_content_Which_startWorkerResponse Message_content_Which = 1
	Message_content_Which_stopWorkerRequest   Message_content_Which = 2
	Message_content_Which_stopWorkerResponse  Message_content_Which = 3
	Message_content_Which_updateWorkerStatus  Message_content_Which = 4
	Message_content_Which_updateWorkerStdio   Message_content_Which = 5
	Message_content_Which_updateClientInfo    Message_content_Which = 6
)

func (w Message_content_Which) String() string {
	const s = "startWorkerRequeststartWorkerResponsestopWorkerRequeststopWorkerResponseupdateWorkerStatusupdateWorkerStdioupdateClientInfo"
	switch w {
	case Message_content_Which_startWorkerRequest:
		return s[0:18]
	case Message_content_Which_startWorkerResponse:
		return s[18:37]
	case Message_content_Which_stopWorkerRequest:
		return s[37:54]
	case Message_content_Which_stopWorkerResponse:
		return s[54:72]
	case Message_content_Which_updateWorkerStatus:
		return s[72:90]
	case Message_content_Which_updateWorkerStdio:
		return s[90:107]
	case Message_content_Which_updateClientInfo:
		return s[107:123]

	}
	return "Message_content_Which(" + strconv.FormatUint(uint64(w), 10) + ")"
}

// Message_TypeID is the unique identifier for the type Message.
const Message_TypeID = 0xd270ea7f372f79cd

func NewMessage(s *capnp.Segment) (Message, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Message(st), err
}

func NewRootMessage(s *capnp.Segment) (Message, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Message(st), err
}

func ReadRootMessage(msg *capnp.Message) (Message, error) {
	root, err := msg.Root()
	return Message(root.Struct()), err
}

func (s Message) String() string {
	str, _ := text.Marshal(0xd270ea7f372f79cd, capnp.Struct(s))
	return str
}

func (s Message) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Message) DecodeFromPtr(p capnp.Ptr) Message {
	return Message(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Message) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Message) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Message) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Message) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Message) Content() Message_content { return Message_content(s) }

func (s Message_content) Which() Message_content_Which {
	return Message_content_Which(capnp.Struct(s).Uint16(0))
}
func (s Message_content) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Message_content) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Message_content) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Message_content) StartWorkerRequest() (StartWorkerRequest, error) {
	if capnp.Struct(s).Uint16(0) != 0 {
		panic("Which() != startWorkerRequest")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return StartWorkerRequest(p.Struct()), err
}

func (s Message_content) HasStartWorkerRequest() bool {
	if capnp.Struct(s).Uint16(0) != 0 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Message_content) SetStartWorkerRequest(v StartWorkerRequest) error {
	capnp.Struct(s).SetUint16(0, 0)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewStartWorkerRequest sets the startWorkerRequest field to a newly
// allocated StartWorkerRequest struct, preferring placement in s's segment.
func (s Message_content) NewStartWorkerRequest() (StartWorkerRequest, error) {
	capnp.Struct(s).SetUint16(0, 0)
	ss, err := NewStartWorkerRequest(capnp.Struct(s).Segment())
	if err != nil {
		return StartWorkerRequest{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Message_content) StartWorkerResponse() (StartWorkerResponse, error) {
	if capnp.Struct(s).Uint16(0) != 1 {
		panic("Which() != startWorkerResponse")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return StartWorkerResponse(p.Struct()), err
}

func (s Message_content) HasStartWorkerResponse() bool {
	if capnp.Struct(s).Uint16(0) != 1 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Message_content) SetStartWorkerResponse(v StartWorkerResponse) error {
	capnp.Struct(s).SetUint16(0, 1)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewStartWorkerResponse sets the startWorkerResponse field to a newly
// allocated StartWorkerResponse struct, preferring placement in s's segment.
func (s Message_content) NewStartWorkerResponse() (StartWorkerResponse, error) {
	capnp.Struct(s).SetUint16(0, 1)
	ss, err := NewStartWorkerResponse(capnp.Struct(s).Segment())
	if err != nil {
		return StartWorkerResponse{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Message_content) StopWorkerRequest() (StopWorkerRequest, error) {
	if capnp.Struct(s).Uint16(0) != 2 {
		panic("Which() != stopWorkerRequest")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return StopWorkerRequest(p.Struct()), err
}

func (s Message_content) HasStopWorkerRequest() bool {
	if capnp.Struct(s).Uint16(0) != 2 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Message_content) SetStopWorkerRequest(v StopWorkerRequest) error {
	capnp.Struct(s).SetUint16(0, 2)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewStopWorkerRequest sets the stopWorkerRequest field to a newly
// allocated StopWorkerRequest struct, preferring placement in s's segment.
func (s Message_content) NewStopWorkerRequest() (StopWorkerRequest, error) {
	capnp.Struct(s).SetUint16(0, 2)
	ss, err := NewStopWorkerRequest(capnp.Struct(s).Segment())
	if err != nil {
		return StopWorkerRequest{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Message_content) StopWorkerResponse() (StopWorkerResponse, error) {
	if capnp.Struct(s).Uint16(0) != 3 {
		panic("Which() != stopWorkerResponse")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return StopWorkerResponse(p.Struct()), err
}

func (s Message_content) HasStopWorkerResponse() bool {
	if capnp.Struct(s).Uint16(0) != 3 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Message_content) SetStopWorkerResponse(v StopWorkerResponse) error {
	capnp.Struct(s).SetUint16(0, 3)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewStopWorkerResponse sets the stopWorkerResponse field to a newly
// allocated StopWorkerResponse struct, preferring placement in s's segment.
func (s Message_content) NewStopWorkerResponse() (StopWorkerResponse, error) {
	capnp.Struct(s).SetUint16(0, 3)
	ss, err := NewStopWorkerResponse(capnp.Struct(s).Segment())
	if err != nil {
		return StopWorkerResponse{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Message_content) UpdateWorkerStatus() (UpdateWorkerStatus, error) {
	if capnp.Struct(s).Uint16(0) != 4 {
		panic("Which() != updateWorkerStatus")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return UpdateWorkerStatus(p.Struct()), err
}

func (s Message_content) HasUpdateWorkerStatus() bool {
	if capnp.Struct(s).Uint16(0) != 4 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Message_content) SetUpdateWorkerStatus(v UpdateWorkerStatus) error {
	capnp.Struct(s).SetUint16(0, 4)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewUpdateWorkerStatus sets the updateWorkerStatus field to a newly
// allocated UpdateWorkerStatus struct, preferring placement in s's segment.
func (s Message_content) NewUpdateWorkerStatus() (UpdateWorkerStatus, error) {
	capnp.Struct(s).SetUint16(0, 4)
	ss, err := NewUpdateWorkerStatus(capnp.Struct(s).Segment())
	if err != nil {
		return UpdateWorkerStatus{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Message_content) UpdateWorkerStdio() (UpdateWorkerStdio, error) {
	if capnp.Struct(s).Uint16(0) != 5 {
		panic("Which() != updateWorkerStdio")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return UpdateWorkerStdio(p.Struct()), err
}

func (s Message_content) HasUpdateWorkerStdio() bool {
	if capnp.Struct(s).Uint16(0) != 5 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Message_content) SetUpdateWorkerStdio(v UpdateWorkerStdio) error {
	capnp.Struct(s).SetUint16(0, 5)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewUpdateWorkerStdio sets the updateWorkerStdio field to a newly
// allocated UpdateWorkerStdio struct, preferring placement in s's segment.
func (s Message_content) NewUpdateWorkerStdio() (UpdateWorkerStdio, error) {
	capnp.Struct(s).SetUint16(0, 5)
	ss, err := NewUpdateWorkerStdio(capnp.Struct(s).Segment())
	if err != nil {
		return UpdateWorkerStdio{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Message_content) UpdateClientInfo() (UpdateClientInfo, error) {
	if capnp.Struct(s).Uint16(0) != 6 {
		panic("Which() != updateClientInfo")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return UpdateClientInfo(p.Struct()), err
}

func (s Message_content) HasUpdateClientInfo() bool {
	if capnp.Struct(s).Uint16(0) != 6 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Message_content) SetUpdateClientInfo(v UpdateClientInfo) error {
	capnp.Struct(s).SetUint16(0, 6)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewUpdateClientInfo sets the updateClientInfo field to a newly
// allocated UpdateClientInfo struct, preferring placement in s's segment.
func (s Message_content) NewUpdateClientInfo() (UpdateClientInfo, error) {
	capnp.Struct(s).SetUint16(0, 6)
	ss, err := NewUpdateClientInfo(capnp.Struct(s).Segment())
	if err != nil {
		return UpdateClientInfo{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// Message_List is a list of Message.
type Message_List = capnp.StructList[Message]

// NewMessage creates a new list of Message.
func NewMessage_List(s *capnp.Segment, sz int32) (Message_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[Message](l), err
}

// Message_Future is a wrapper for a Message promised by a client call.
type Message_Future struct{ *capnp.Future }

func (f Message_Future) Struct() (Message, error) {
	p, err := f.Future.Ptr()
	return Message(p.Struct()), err
}
func (p Message_Future) Content() Message_content_Future { return Message_content_Future{p.Future} }

// Message_content_Future is a wrapper for a Message_content promised by a client call.
type Message_content_Future struct{ *capnp.Future }

func (f Message_content_Future) Struct() (Message_content, error) {
	p, err := f.Future.Ptr()
	return Message_content(p.Struct()), err
}
func (p Message_content_Future) StartWorkerRequest() StartWorkerRequest_Future {
	return StartWorkerRequest_Future{Future: p.Future.Field(0, nil)}
}
func (p Message_content_Future) StartWorkerResponse() StartWorkerResponse_Future {
	return StartWorkerResponse_Future{Future: p.Future.Field(0, nil)}
}
func (p Message_content_Future) StopWorkerRequest() StopWorkerRequest_Future {
	return StopWorkerRequest_Future{Future: p.Future.Field(0, nil)}
}
func (p Message_content_Future) StopWorkerResponse() StopWorkerResponse_Future {
	return StopWorkerResponse_Future{Future: p.Future.Field(0, nil)}
}
func (p Message_content_Future) UpdateWorkerStatus() UpdateWorkerStatus_Future {
	return UpdateWorkerStatus_Future{Future: p.Future.Field(0, nil)}
}
func (p Message_content_Future) UpdateWorkerStdio() UpdateWorkerStdio_Future {
	return UpdateWorkerStdio_Future{Future: p.Future.Field(0, nil)}
}
func (p Message_content_Future) UpdateClientInfo() UpdateClientInfo_Future {
	return UpdateClientInfo_Future{Future: p.Future.Field(0, nil)}
}

const schema_dcccaa5d36aa8b70 = "x\xda\x8c\x96o\x88\x14e\x1c\xc7\x7f\xbf\xe7\x99\xb9Y" +
	"\xe4\xd6\xdbi60P\xec\x04_t\xd0\x9ezT\xe0" +
	"\x9bs\xcf[cM\xbd\x9d\x9d=.%\xc1\xb9\xdbQ" +
	"\xaf\xbb\x9b\x19\xe7\x99-\x0f\x85+\x88\xfe\x18Q\x1a\x17" +
	"\x19\x82\"Z*\x85\x1e\x19XD%(\x99y F" +
	"P\xa1\xc5\x91\xff\xf1\x8de\xa0\xa5M<3\xbb;\xfb" +
	"\xe7\xae\xbbw;\x0f\x9f\xf9\xcc\xf7y\x9e\xdf\xefyv" +
	"\xd1y\xb2LX\x1c\xbd\xd6\x00D\xcd\x88\x0d\xde\xfd\xb3" +
	"W\x1e\x9b\xf8\xf6\xd0k \xcf\x11<\xfb\xcd#O\xae" +
	"?r\xee\"\x00\xb6\xad\xa5\xbd\xa8\x0cQ\x09@\xdbL" +
	")j.%\x08\xe0\xedI\xb6m\x1f\xff\xfc\xc4\x8e:" +
	"~\x98\xb6\xa0\xf2\x86\xcf\xbf\xc2\xf9w\x02\xfe.;3" +
	"r\xb59\xf7n\x1d\xbf\x93\xaeC\xe5\xa0\xcf\xef\xe3\xfc" +
	"\xc7\x01\x7fn49\x91\xe880Z\xc7\x8f\xd1,*" +
	"\xa7}\xfe\x1b\xce\x9f\x0b\xf8\x81=W\x0f$\xe8\xae\xf7" +
	"A\x9e\x83!/r\xaem\x9c\x7fb\x82\xffT.\xd1" +
	"\xa3\x80\xde\xb1\xefw\x9fh\x1ac\xfbj`\x81\xc3\xa3" +
	"\xc2JT\x0e\xf3\x9f\xcaA\xe1\x1a\xa0\xf7\xdb\x8f{\xe7" +
	"\xa2\xdd\xf2!\xa8s\xb0\x82\xf6\xe1\x97\xc5u\xa8\x8c\x8a" +
	"\x1c\xde)\xb6\x03z\xbd7\x0e\x0b\xef-}\xfe\xa3\x1a" +
	"3rxL\xe4\xc9}\xf8\xa4\x0f'\xe9\xab\xaf\x1f\xdf" +
	"\xda\x7f\xb4n\x8e\x13\xe2\x02TnsR\xbb%R\xd4" +
	"\xee\x8a\xfe\x1c\x8f\xfd\x902\x0fu>7V-\xf7\x83" +
	"\xdc\xe3\xeeh\x83\x04\xd4\x93\x8f\xf4<\xb2\xbf\xd58\x0e" +
	"\xea\xa3\x88\xde\xf8p\xebS#7\xed\x0b\xd0\x8d\x92\x9f" +
	"\xe2\x86\xd8\x81\x80m\xb7\xc5\xb7\x11\xd0;\xb0\xf1\xeb\xdd" +
	"\xf3.\xff\xf1E\xfd2KKP9)\xf1\x08_J" +
	"\x14\xb53\x92\x1f\xa1\xa3w\xd1\xadY\xdb^\xfa\xaa\x8e" +
	"\xffN\xca\xa2r\xc9\xe7\x7f\xe2\xfc\xe5\x80\x7f\xeb\xd0\xde" +
	"?\xb7\x09wNO\xb6\x1eW\xa4^T\xee\xf1W\x94" +
	"\xbf$\xbe\x1e\xe5\xac\xd5+\x1d\xd0\x0fG\x08*\xcd\x11" +
	"N\xcf\x8bp\xfaSv\xab\xf9\xf7O\x0e\xff:\x99\xba" +
	"9\xb2\x0e\x95'|xq\xa4\x1d\x1e\xf7l\xc7r\xad" +
	"\xd6>]\xb0M\xbb\xd5\x7fH\xf4\xe9\xb6i/-\xd8" +
	"y\xdd5z,g\xc0p4Ww\xa5\x02\xcbe\x10" +
	"\xb1\x11\x086\x02,\xc6\x87\xd0[\xb12\x91\xcc\xa4\x13" +
	"=\xb4+\xfbL*\x9b\xe8\xcet&s\xa9\x84\x96K" +
	"\xe6\xba\xb5\xc4B\x96X\x88\xac\xfc\x01Z\xfb\x01\xe6\xea" +
	"\x8e\xdbc9M\x03\x86Si\x96\xf1BYL\x02\xb1" +
	"\x96Kfs\xb5\xc2\xba\xc4/:\xfda\xe0\xbcU\xa0" +
	"nu\xe0Yu\x81{\xb2i?ogWw\xa0g" +
	"\x003\xf5\xf7\x9bX\xad'\xa1>R\xa3O\xaf)\xda" +
	"K\xeeZ\xb5V\\\x8b\x01\xc3\xc9\x1a[\x0a\x06en" +
	"\x06Qm\xa4\x02\x80\x80\x00r\xaa\x03@]FQ]" +
	"EPF\x8c#\x1fL\xb7\x00\xa8\x9d\x14\xd5\x0d\x04e" +
	"B\xe2H\x00\xe4\xf5\x0b\x00\xd4g)\xaa.\xc1\x91>" +
	"khH7\xf3\xc5\x90\xd8\xa4;\x9b\x18\xce\x06\xcc\xd0" +
	" \xf8l@\xc90_\xa8\x19\x9az\x09\xba\xfd\xa2X" +
	">\xd8o\x98n\xda\xdch\x01\xf0\x98\xb1rL}%" +
	"\x80\xba\x81\xa2:X\x11\xb3\x9f\x0fn\x0e\x12\x95cn" +
	"Y\x0a\xa0\x0eRT\xb7\x12\x94)\x8d#\x05\x90\x0b|" +
	"\x966Eu;A\xaf\xc0\x0c\xc7\xd4\x87\x0c\x00(\xe5" +
	"\xf76[\xcc\xad\x19kg\xc3\xcc5\x86J\x8f#z" +
	">\xef\x18\x8c\x95_\x99f.a\x81\xd3\x02\xe3\x93\x11" +
	"\xca\x93\x89\xf2\x88\x11\x8aj\x9c`;su\xb7\xc0P" +
	"\x04\x82\xe2\xcc\xad\xf9~\xb4j\xa4-\xa1\xb4)\xaf\xbb" +
	":F\x81`\xb4B9I\xa3X6\x17J\xb5}r" +
	"\xb6\xbeO\xba2\xd3\xd7\xb1V\xf4\x15k\x8d!\xaf\xb5" +
	"\xa9\xf1\xd5\x06c\xfa&#\xd1g\x99\xaea\xba\xa0\xce" +
	"\xa5B\xa3\xe7\xf9\xb3\xf9\xec\x03\x00\xf5\x04E\xf5\x14\xc1" +
	"(\xfe\xeb\x05\x1b~r?\x80z\x8a\xa2z\x9e`\x94" +
	"<\xf0\x82\x1d\x1f\xdf\x05\xa0\x9e\xa7\xa8^$\x18\xa5\xf7" +
	"\xbd`\xcb\x7f\xe6\x86\x8b\x14\xd5\xeb\x04\xa3\xc2?^\x1c" +
	"\x05\x00\xf9\x0a\x1f\xbdNQ\xbdC0*\xfe\xed\xc5Q" +
	"\x04\x90os\xc3\x1d\x8aY$\x18m\xb8\xe7\xc5\xb1\x01" +
	"@~\xb0\x03 \x8b\x14\xb5F\xde\x82\xa5S\x05+Z" +
	"\x09c\xe1-\x08\x881\xa8\xc5\x98mI&30\x16" +
	"\x1e\xcbe.X+\x0c\x17\x0bc\xe1}3\x19\xc5l" +
	"\xcb\xa4\xbe\xac|\x10\x17\xb1\xd2\x91\x8a\x15%\x87\xb1\xf0" +
	"\x1e\x9d\x1c\xe35\x84\xb1\xf0\x02\xad\xa2\x96\x0fb\xd8\x8b" +
	"<Y\xe9\x02/RS\x16\x95c\xd8\x83\xc3\xab\x0d6" +
	"\x9f\xefmuY\xfdR*\xab\xd5$\xa5i\xc9\xa7S" +
	"\x89l*\xb3j-/,\xba\x90Mwc\x84\x87\x03" +
	"Vko\x96\xb4\xcb\xc9\xaatjM\xaet]\xa4\xd7" +
	"\xach\xeaJ\xfc\x9f\xb8\xeat,\xeeUMW-\x09" +
	"\xbbj\xbe\xe18\x96S\xd7\xfft\x8a\xba\x86\xb2\x091" +
	"\xfc\x8b G;\x80\x8c\x14K~f\xadT\xdc\xf7\x99" +
	"\x06\xfb/\x00\x00\xff\xff\x96\xa5\x05\x9b"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_dcccaa5d36aa8b70,
		Nodes: []uint64{
			0x87a8c7e129e5cafc,
			0x8ab8b9cd7c33419c,
			0x935421e67fc873f8,
			0x95a4422ee14195cc,
			0x9892032ea4e69c6b,
			0xa073b10fb899cbb0,
			0xa62a70011c9fd5df,
			0xa76a3a9604a9e962,
			0xaf6978b488860341,
			0xb15c44a86e45d3b0,
			0xb4652fa21957aa11,
			0xbaf2e41d99bf66a4,
			0xbe807b0aec306242,
			0xc5f4047bf39fa88d,
			0xd270ea7f372f79cd,
			0xdea9ade321ec73b3,
		},
		Compressed: true,
	})
}
