// Code generated by go generate; DO NOT EDIT.
package config

const (
	NatsURL = "wss://localhost"
	NatsUser = "vessel"
	NatsPassword = "vesselpassword"
)

const (
	ConnectorName = "vessel"
	ConnectorVersion = "0.1.0"
)
