// Code generated by go generate; DO NOT EDIT.
package config

const (
	ServerURL = "wss://localhost"
	ServerUsername = "vessel"
	ServerPassword = "vesselpassword"
)

const (
	ServiceName = "vessel"
	ServiceWorkerName = "vessel-worker"
	ServiceVersion = "1.0.0"
)
